### ISSUE TITLE
Confused on Several HTTP/HTTPS rules

### ISSUE THREAD

**Issue by da667** [nsacyber/ELITEWOLF#4]
Hello,

My name is Tony, I work on the Proofpoint Emerging Threats team. Before I go any further, thank you very much for sharing these IDS rules with the community. I have a couple of questions and observations to add to the rules you've provided in hopes of making an already good contribution that much better.

This issue is actually two issues, or questions, I was hoping you might be able to shed light on.
____
# Question 1: Is the rule header direction for HTTP and HTTPS rules requesting specific URIs correct?

Several of the HTTP and HTTPS rules utilize URIs for detection. The rule headers for these rules looks like:
`alert any 80 -> any any`

Which in snort methodology is: "look at traffic where the source IP is anything, the source port is 80 and the destination is any IP address and any port"

This doesn't make sense to me. If the goal of these rules is to capture access attempts to HMI/ICS devices, shouldn't the header be:

`alert any any -> any 80`

Which in snort methodology is "Look at traffic from any source IP address any source port, heading towards the destination IP address on port 80. The external client should be requesting the given URI on the server, right?

___
# Question/Observation 2: Many of the HTTP/HTTPS rules to URI endpoints don't specify what kind of HTTP method is being used (e.g. GET, POST, etc.). Additionally, the `flow` keyword is not being used.

Based on my understanding, many of these URI requests to detect reconnaissance and/or unauthorized access are going to be GET requests for specific resources or pages that identify an asset as an HMI or Controller device. Adding the following content match to those rules:

`content:"GET"; http_method;`

If included as a part of a larger ruleset, this content match will help funnel rules into smaller buckets and ensure they are checked less frequently. Putting it another way, let me use one of the provided rules as an example

`alert tcp any 80 -> any any (msg: "ELITEWOLF S7-1200 Possible Siemens Web Activity"; content:"/Images/CPU1200/"; sid:1; rev:1;)`

Now, assuming that point 1 above is correct, and we're looking for GET requests to this URI, here are my proposed changes:

`alert tcp any any -> any 80 (msg: "ELITEWOLF S7-1200 Possible Siemens Web Activity"; flow:established,to_server; content:"GET"; http_method; content:"/Images/CPU1200/"; sid:1; rev:1;)`

Changes:
- Added the flow keyword to indicate that a three-way handshake should be established, and this HTTP request should be flowing towards the HTTP server
- Added the `content:"GET"; http_method;` content match. This means that this rule will only attempt to find HTTP GET requests, and not blindly search for the URI, or respond to POST, TRACE, HEAD, OPTIONS, or other http request methods.

Utilizing the `flow` keyword and the `http_method` content match means that, as a part of a larger ruleset, that these rules will be checked less frequently. and thus will perform better.

I hope to submit a pull request with my proposed changes, as well as my results from porting the provided rules to Suricata 4, and 5+ very soon.

Cheers,

Tony/DA667

**Comment by iadgovuser52** [comment]
Thank you for your interest and questions. The directionality in the rules is intentional to detect device responses rather than requests to devices, so specifying the source port as 80 is correct and the `http_method` doesn't apply. Looking for responses can also reduce false positives. We'll consider using the `flow` keyword for future rules.
